line-length = 119
[format]
quote-style = "single"

[lint]
ignore = [
    "ANN",
    "D",
    "SIM105",
    "PGH004",
    "PTH",
    "ERA001",
    "ISC001",
    "COM812",
]
select = ["ALL"]

[lint.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "double"

[lint.per-file-ignores]
"tests/**" = ["S101", "S603", "PLR2004", "PT011", "B017", "F841", "FBT003", "PLC0415"]

[lint.pylint]
max-args = 10
